name: Unit tests

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "*"

jobs:
  windows-run:
    name: Run CI on Windows
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: "windows-latest"

    env:
      CI: 1
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DEBUG: ${{ secrets.DEBUG }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: pip

      - name: Lint
        run: |
          pip install black>=20.8b1
          black --check .

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          bash scripts/start-docker-postgres.sh
          sleep 5 # wait for postgres to start
          bash scripts/run-tests.sh

  macos-run:
    name: Run CI on macOS 12
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: "macos-latest"

    env:
      CI: 1
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DEBUG: ${{ secrets.DEBUG }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: pip

      - name: Lint
        run: |
          pip install black>=20.8b1
          black --check .

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          bash scripts/start-docker-postgres.sh
          sleep 5 # wait for postgres to start
          bash scripts/run-tests.sh

  ubuntu-run:
    name: Run CI on Ubuntu
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: "ubuntu-latest"

    env:
      CI: 1
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DEBUG: ${{ secrets.DEBUG }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: pip

      - name: Lint
        run: |
          pip install black>=20.8b1
          black --check .

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          bash scripts/start-docker-postgres.sh
          sleep 5 # wait for postgres to start
          bash scripts/run-tests.sh
