# Generated by Django 4.0.6 on 2022-07-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolphin', '0002_machine_remove_log_architecture_bits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='machine',
            new_name='machine_id',
        ),
    ]
