# Generated by Django 4.0.6 on 2022-07-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolphin', '0003_rename_machine_log_machine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='libc_lib',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='libc_version',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='release',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='versioninfo',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='win32_edition',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='win32_is_iot',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='win32_ver_csd',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='win32_ver_ptype',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='win32_ver_release',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='win32_ver_version',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
