# Generated by Django 4.0.6 on 2022-07-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolphin', '0004_alter_machine_libc_lib_alter_machine_libc_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='architecture_linkage',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
