# Generated by Django 4.0.6 on 2022-07-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolphin', '0005_alter_machine_architecture_linkage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='all_disk_partitions',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='cpu_freq',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='cpu_percent',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='cpu_times',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='cpu_times_percent',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='disk_io_counters_per_disk',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='disk_partitions',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='network_io_counters_per_nic',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='versioninfo',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
