# Generated by Django 4.0.6 on 2022-07-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolphin', '0006_alter_log_all_disk_partitions_alter_log_cpu_freq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='sensors_fans',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='sensors_temperatures',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
